name: Deploy app to AWS
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop, dependency_updates]

jobs:
  deploy_to_S3:
    name: Deploy app to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'
      NEXT_PUBLIC_SENTRY: "https://d48c58a239264c12bcbf8fe86d364c44@o489056.ingest.sentry.io/5799127"
    steps:
      - name: Set release variables
        if: github.ref == 'refs/heads/main'
        run: |
          echo "s3_bucket=s3://skde.org/helseatlas" >> $GITHUB_ENV
      - name: Set QA variables
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "s3_bucket=s3://qa.skde.org/helseatlas" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build package
        run: yarn install && yarn run export
      - name: Sync to S3 bucket
        if: github.event_name != 'pull_request'
        run: |
          aws s3 sync out ${{ env.s3_bucket }} --exclude "ia/*" --exclude "files/*" --delete --cache-control "public, max-age=1, s-maxage=1"
