backend:
  name: github
  repo: mong/hamongts
  branch: netlifyCMS
  base_url: https://qa-mong-api.skde.org

publish_mode: editorial_workflow 
logo_url: https://www.skde.no/img/logos/SKDE_sort.png
media_folder: public/img
public_folder: img
collections:
  - label: "Aktuelt"
    name: "aktuelt"
    folder: "_posts/testatlas"
    create: true
    fields:
      - { label: "Publiseringsdato", name: "date", widget: "datetime" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Ingress", name: "ingress", widget: "text" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Artikkelbilde", name: "thumbnail", widget: "image" }
  - label: "Tidligere atlas"
    name: "tidligere_atlas"
    folder: "_posts/tidligere_atlas"
    create: true
    fields:
      - { label: "Publiseringsdato", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Språk", name: "lang", widget: "string" }
  - label: "Tidligere engelske atlas"
    name: "tidligere_eng_atlas"
    folder: "_posts/en/tidligere_atlas"
    create: true
    fields:
      - { label: "Publiseringsdato", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Språk", name: "lang", widget: "string" }
