backend:
  name: github
  repo: mong/hamongts
  branch: cms-fix
  base_url: https://prod-mong-api.skde.org

publish_mode: editorial_workflow
logo_url: https://qa.skde.no/helseatlas/img/logos/helseatlas.svg
media_folder: public/img
public_folder: img
site_url: https://qa.skde.no/helseatlas/
locale: "nb_no"
collections:
  - label: "Atlas" # Nye atlas
    name: "atlas"
    folder: "_posts/atlas"
    extension: json
    format: json
    create: true
    identifier_field: filename
    widget: "list"
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Publiseringsdato", name: "date", widget: "datetime" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Ingress", name: "ingress", widget: "string" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
          default: "no",
        }
      - label: "Innhold"
        name: "innhold"
        widget: "list"
        types:
          - label: "Tekst"
            name: "tekst"
            widget: object
            field: { label: "Avsnitt", name: "avsnitt", widget: "markdown" }
          - label: "Figur"
            name: "figur"
            widget: object
            field: { label: Image, name: image, widget: image }
          - label: "Faktaboks"
            name: "faktaboks"
            widget: object
            fields:
              - label: "Overskrift"
                name: "overskrift"
                widget: "string"
              - label: "Tekst"
                name: "tekst"
                widget: "markdown"
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            summary: "{{fields.header}}"
            fields:
              - {
                  label: Header,
                  name: header,
                  widget: string,
                  default: "Spotlight",
                }
              - {
                  label: Template,
                  name: template,
                  widget: string,
                  default: "spotlight.html",
                }
              - {
                  label: Text,
                  name: text,
                  widget: text,
                  default: "Hello World",
                }
  - label: "Tidligere atlas"
    name: "tidligere_atlas"
    folder: "_posts/tidligere_atlas"
    create: false
    fields:
      - { label: "Publiseringsnummer", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Innholdsfortegnelse?", name: "toc", widget: "boolean" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
        }
  - label: "Statiske sider"
    name: "statiske_sider"
    folder: "_posts/statisk"
    create: true
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
  - label: "Tidligere engelske atlas"
    name: "tidligere_eng_atlas"
    folder: "_posts/en/tidligere_atlas"
    create: false
    fields:
      - { label: "Publiseringsnummer", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Innholdsfortegnelse?", name: "toc", widget: "boolean" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
        }
  - label: "Statiske engelske sider"
    name: "statiske_sider_en"
    folder: "_posts/en/static"
    create: true
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
