backend:
  name: github
  repo: mong/hamongts
  branch: cms-fix
  base_url: https://qa-mong-api.skde.org

publish_mode: editorial_workflow
logo_url: https://qa.skde.no/helseatlas/img/logos/helseatlas.svg
media_folder: public/img
public_folder: img
site_url: https://qa.skde.no/helseatlas/
locale: "nb_no"
collections:
  - label: "Atlas" # Nye atlas
    name: "atlas"
    folder: "_posts/atlas"
    extension: json
    create: true
    identifier_field: filename
    widget: "list"
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Publiseringsnummer", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
        }
      - label: "Resultatboks"
        name: resultatboks
        widget: "list"
        types:
          - label: "Carousel"
            name: "carousel"
            widget: object
            summary: "{{fields.header}}"
            fields:
              - {
                  label: Header,
                  name: header,
                  widget: string,
                  default: "Image Gallery",
                }
              - {
                  label: Template,
                  name: template,
                  widget: string,
                  default: "carousel.html",
                }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            fields:
              - {
                  label: Header,
                  name: header,
                  widget: string,
                  default: "Spotlight",
                }
              - {
                  label: Template,
                  name: template,
                  widget: string,
                  default: "spotlight.html",
                }
              - {
                  label: Text,
                  name: text,
                  widget: text,
                  default: "Hello World",
                }
  - label: "Tidligere atlas"
    name: "tidligere_atlas"
    folder: "_posts/tidligere_atlas"
    create: false
    fields:
      - { label: "Publiseringsnummer", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Innholdsfortegnelse?", name: "toc", widget: "boolean" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
        }
  - label: "Statiske sider"
    name: "statiske_sider"
    folder: "_posts/statisk"
    create: true
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
  - label: "Tidligere engelske atlas"
    name: "tidligere_eng_atlas"
    folder: "_posts/en/tidligere_atlas"
    create: false
    fields:
      - { label: "Publiseringsnummer", name: "num", widget: "number" }
      - { label: "Tittel", name: "mainTitle", widget: "string" }
      - { label: "Kort tittel", name: "shortTitle", widget: "string" }
      - { label: "Rapport", name: "pdfUrl", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
      - { label: "Instant atlas?", name: "ia", widget: "boolean" }
      - { label: "Innholdsfortegnelse?", name: "toc", widget: "boolean" }
      - {
          label: "Språk",
          name: "lang",
          widget: "select",
          options: ["no", "en"],
        }
  - label: "Statiske engelske sider"
    name: "statiske_sider_en"
    folder: "_posts/en/static"
    create: true
    fields:
      - { label: "Filnavn", name: "filename", widget: "string" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Hovedtekst", name: "body", widget: "markdown" }
