name: Deploy app to AWS
on:
  push:
    branches: [cms-fix]
  pull_request:
    branches: [develop, dependabot_updates]

jobs:
  deploy_to_S3:
    name: Deploy app to S3
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-west-1'
    steps:
      - name: Set release variables
        if: github.ref == 'refs/heads/main'
        run: |
          echo "s3_bucket=s3://skde.org/helseatlas" >> $GITHUB_ENV
      - name: Set QA variables
        if: github.ref == 'refs/heads/cms-fix'
        run: |
          echo "s3_bucket=s3://qa.skde.org/helseatlas" >> $GITHUB_ENV
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build package
        run: yarn install && yarn run export
      - name: Sync to S3 bucket
        if: github.event_name != 'pull_request'
        run: |
          aws s3 sync out ${{ env.s3_bucket }} --delete --cache-control "public, max-age=31536000"
          aws s3 cp out/index.html ${{ env.s3_bucket }}/index.html --cache-control "public, max-age=1, s-maxage=1"